version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: freelance_postgres
    ports:
      - "2006:5432"
    environment:
      POSTGRES_DB: freelance_db
      POSTGRES_USER: freelance_user
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: freelance_backend
    ports:
      - "5500:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      FLASK_ENV: production
      DB_URI: postgresql://freelance_user:strongpassword@postgres:5432/freelance_db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: freelance_frontend
    ports:
      - "8088:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
